### ISSUE TITLE
Full access to VAG-API

### ISSUE THREAD

**Issue by mymindwentblvnk** [derphilipp/vagquery#2]
Hi Philipp, 

do you know how to access the Fahrten API (see [http://start.vag.de/dm/](http://start.vag.de/dm/))? 
And do you know how to search Haltestellen by other paramaters than Haltestellen name? For example by latitude and longitude?

Thanks for the nice script!
Greetings, 

Michael

**Comment by derphilipp** [comment]
Thank you, 

I was not aware of the API, that is really nice!
If you have any code suggestions to the module I would be very happy to accept it;

Cheers,

Philipp

**Comment by mymindwentblvnk** [comment]
I tried to contact the company that is responsible for the API but no answer. Maybe directly contacting the VAG helps. 
If they would give us any API documentation I would be very happy to contribute to your project. 

Michael

**Comment by mymindwentblvnk** [comment]
Here is the API in action: 
* https://www.vag.de/fahrplan.html
* http://www.vgn.de/komfortauskunft/haltestelle/

I try to get more information about the JSON calls at home.
